export enum BookGenre {
    FANTASY = "FANTASY",
    DRAMA = "DRAMA",
    ROMANCE = "ROMANCE",
    THRILLER = "THRILLER",
    SCIENCE_FICTION = "SCIENCE_FICTION",
    MYSTERY = "MYSTERY",
    HORROR = "HORROR",
    HISTORICAL = "HISTORICAL",
    ADVENTURE = "ADVENTURE",
    NON_FICTION = "NON_FICTION",
    POETRY = "POETRY",
    BIOGRAPHY = "BIOGRAPHY",
    CHILDRENS = "CHILDRENS",
    YOUNG_ADULT = "YOUNG_ADULT",
    CLASSIC = "CLASSIC"
  }